### ISSUE TITLE
麻烦您重新改个算法在写死ID

### ISSUE THREAD

**Issue by wy414012** [diskcoin-apps-team/wiki#1]
@diskcoin-apps-team  格局如此之小么写死扫盘软件 你要是重新改个算法还行不要拿着源码想些占据主导问题

**Comment by diskcoin-apps-team** [comment]
The version of 0714 has already been compatible with blago, and our miner will open source later. 
You can download the latest miner here: https://github.com/diskcoin-apps-team/wiki/releases/tag/v0714

**Comment by wy414012** [comment]
@diskcoin-apps-team 不要自己写入ID位数长短限制 国产为了GDP没有容量你拿什么赚GDP都是一个算法生成的ID 好好的搞好项目！~几十P  重新P盘不是那么容易请动的 ，别浪费我群里面大户们的心情
